# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-09 04:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20170502_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='peters_field',
            field=models.CharField(default='Mere Words!', max_length=100),
        ),
    ]
